//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARCHIVED_STUDENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARCHIVED_STUDENT()
        {
            this.ARCHIVED_EXAM_SCORE = new HashSet<ARCHIVED_EXAM_SCORE>();
            this.ARCHIVED_GUARDIAN = new HashSet<ARCHIVED_GUARDIAN>();
        }
    
        public int ID { get; set; }
        public string ADMSN_NO { get; set; }
        public string CLS_ROLL_NO { get; set; }
        public Nullable<System.DateTime> ADMSN_DATE { get; set; }
        public string FIRST_NAME { get; set; }
        public string MID_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public Nullable<int> BTCH_ID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string GNDR { get; set; }
        public string BLOOD_GRP { get; set; }
        public string BIRTH_PLACE { get; set; }
        public Nullable<int> NTLTY_ID { get; set; }
        public string LANG { get; set; }
        public string RLGN { get; set; }
        public string ADDR_LINE1 { get; set; }
        public string ADDR_LINE2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string PIN_CODE { get; set; }
        public Nullable<int> CTRY_ID { get; set; }
        public string PH1 { get; set; }
        public string PH2 { get; set; }
        public string EML { get; set; }
        public string PHTO_FILENAME { get; set; }
        public string PHTO_CNTNT_TYPE { get; set; }
        public string PHTO_DATA { get; set; }
        public string STAT_DESCR { get; set; }
        public Nullable<bool> IS_ACT { get; set; }
        public Nullable<bool> IS_DEL { get; set; }
        public Nullable<int> IMMDT_CNTCT_ID { get; set; }
        public Nullable<bool> IS_SMS_ENABL { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
        public Nullable<int> PHTO_FILE_SIZE { get; set; }
        public Nullable<int> FRM_ID { get; set; }
        public Nullable<int> STDNT_CAT_ID { get; set; }
        public string LIBRARY_CARD { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual STUDENT_CATGEORY STUDENT_CATGEORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARCHIVED_EXAM_SCORE> ARCHIVED_EXAM_SCORE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARCHIVED_GUARDIAN> ARCHIVED_GUARDIAN { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
