//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTENDENCE
    {
        public int ID { get; set; }
        public Nullable<int> STDNT_ID { get; set; }
        public Nullable<int> PER_TABLE_ENT_ID { get; set; }
        public string FORENOON { get; set; }
        public string PM { get; set; }
        public string RSN { get; set; }
        public Nullable<System.DateTime> MONTH_DATE { get; set; }
        public Nullable<int> BTCH_ID { get; set; }
    
        public virtual BATCH BATCH { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
