//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCE_WEIGHTAGE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CCE_WEIGHTAGE()
        {
            this.CCE_WEIGHTAGES_COURSE = new HashSet<CCE_WEIGHTAGES_COURSE>();
        }
    
        public int ID { get; set; }
        public Nullable<int> WTAGE { get; set; }
        public string CRITA_TYPE { get; set; }
        public Nullable<int> CCE_EXAM_CAT_ID { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
    
        public virtual CCE_EXAM_CATEGORY CCE_EXAM_CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCE_WEIGHTAGES_COURSE> CCE_WEIGHTAGES_COURSE { get; set; }
    }
}
