//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCE_GRADE
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<double> GRADE_PT { get; set; }
        public Nullable<int> CCE_GRADE_SET_ID { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
    
        public virtual CCE_GRADE_SET CCE_GRADE_SET { get; set; }
    }
}
