//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASS_DESIGNATION
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> CGPA { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
        public Nullable<decimal> MKS { get; set; }
        public Nullable<int> CRS_ID { get; set; }
    
        public virtual COURSE COURSE { get; set; }
    }
}
