//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASS_TIMING_ENTRY
    {
        public int ID { get; set; }
        public Nullable<int> CLASS_TIMING_SET_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<System.TimeSpan> START_TIME { get; set; }
        public Nullable<System.TimeSpan> END_TIME { get; set; }
        public bool IS_BRK { get; set; }
        public bool IS_DEL { get; set; }
    
        public virtual CLASS_TIMING_SET CLASS_TIMING_SET { get; set; }
    }
}
