//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE_ATTENDENCES
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> ATNDENCE_DATE { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<int> EMP_LEAVE_TYPE_ID { get; set; }
        public string RSN { get; set; }
        public string IS_HALF_DAY { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual EMPLOYEE_LEAVE_TYPE EMPLOYEE_LEAVE_TYPE { get; set; }
    }
}
