//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXAM()
        {
            this.ASSESSMENT_SCORE = new HashSet<ASSESSMENT_SCORE>();
            this.CCE_REPORTS = new HashSet<CCE_REPORTS>();
            this.EXAM_SCORE = new HashSet<EXAM_SCORE>();
        }
    
        public int ID { get; set; }
        public Nullable<int> EXAM_GRP_ID { get; set; }
        public Nullable<int> SUBJ_ID { get; set; }
        public Nullable<System.DateTime> START_TIME { get; set; }
        public Nullable<System.DateTime> END_TIME { get; set; }
        public Nullable<int> MAX_MKS { get; set; }
        public Nullable<int> MIN_MKS { get; set; }
        public Nullable<int> GRADING_LVL_ID { get; set; }
        public Nullable<int> WTAGE { get; set; }
        public Nullable<int> EV_ID { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSESSMENT_SCORE> ASSESSMENT_SCORE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCE_REPORTS> CCE_REPORTS { get; set; }
        public virtual EVENT EVENT { get; set; }
        public virtual EXAM_GROUP EXAM_GROUP { get; set; }
        public virtual SUBJECT SUBJECT { get; set; }
        public virtual GRADING_LEVEL GRADING_LEVEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXAM_SCORE> EXAM_SCORE { get; set; }
    }
}
