//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class FA_CRITERIAS
    {
        public int ID { get; set; }
        public string FA_NAME { get; set; }
        public string DESCR { get; set; }
        public Nullable<int> FA_GRP_ID { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
        public Nullable<int> SRT_ORD { get; set; }
        public string IS_DEL { get; set; }
    
        public virtual FA_GROUP FA_GROUP { get; set; }
    }
}
