//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINANCE_FEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FINANCE_FEE()
        {
            this.FINANCE_TRANSACTION = new HashSet<FINANCE_TRANSACTION>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FEE_CLCT_ID { get; set; }
        public string TRAN_ID { get; set; }
        public Nullable<int> STDNT_ID { get; set; }
        public string IS_PD { get; set; }
    
        public virtual FINANCE_FEE_COLLECTION FINANCE_FEE_COLLECTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FINANCE_TRANSACTION> FINANCE_TRANSACTION { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
