//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINANCE_TRANSACTION_TRIGGERS
    {
        public int ID { get; set; }
        public Nullable<int> FIN_CAT_ID { get; set; }
        public Nullable<decimal> PCT { get; set; }
        public string TIL { get; set; }
        public string DESCR { get; set; }
    
        public virtual FINANCE_FEE_CATGEORY FINANCE_FEE_CATGEORY { get; set; }
    }
}
