//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class GALLERY_MASTER
    {
        public long ID { get; set; }
        public string GALLERY_NAME { get; set; }
        public string GALLERY_DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
    }
}
