//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class GALLERY_TAGS
    {
        public int ID { get; set; }
        public Nullable<int> MEM_ID { get; set; }
        public string MEM_TYPE { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
        public Nullable<int> GAL_PHTO_ID { get; set; }
    
        public virtual GALLERY_PHOTOS GALLERY_PHOTOS { get; set; }
    }
}
