//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery_Master
    {
        public long Id { get; set; }
        public string Gallery_Name { get; set; }
        public string Gallery_Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
