//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADING_LEVEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRADING_LEVEL()
        {
            this.ARCHIVED_EXAM_SCORE = new HashSet<ARCHIVED_EXAM_SCORE>();
            this.EXAMs = new HashSet<EXAM>();
            this.EXAM_SCORE = new HashSet<EXAM_SCORE>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> BTCH_ID { get; set; }
        public Nullable<int> MIN_SCORE { get; set; }
        public Nullable<int> ORD { get; set; }
        public bool IS_DEL { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
        public Nullable<decimal> CRED_PT { get; set; }
        public string DESCR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARCHIVED_EXAM_SCORE> ARCHIVED_EXAM_SCORE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXAM> EXAMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXAM_SCORE> EXAM_SCORE { get; set; }
        public virtual BATCH BATCH { get; set; }
    }
}
