//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP_FILE
    {
        public int ID { get; set; }
        public Nullable<int> GROUP_ID { get; set; }
        public Nullable<int> USRID { get; set; }
        public string FILE_DESCR { get; set; }
        public Nullable<int> GROUP_POST_ID { get; set; }
        public string DOC_FILE_NAME { get; set; }
        public string DOC_CNTNT_TYPE { get; set; }
        public Nullable<long> DOC_FILE_SIZE { get; set; }
        public Nullable<System.DateTime> DOC_UPDATED_AT { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
    
        public virtual GROUP GROUP { get; set; }
        public virtual GROUP_POST GROUP_POST { get; set; }
    }
}
