//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GROUP()
        {
            this.GROUP_FILE = new HashSet<GROUP_FILE>();
            this.GROUP_MEMBER = new HashSet<GROUP_MEMBER>();
            this.GROUP_POST = new HashSet<GROUP_POST>();
        }
    
        public int ID { get; set; }
        public string GROUP_NAME { get; set; }
        public string GROUP_DESCR { get; set; }
        public Nullable<int> USRID { get; set; }
        public string LOGO_FILE_NAME { get; set; }
        public string LOGO_CNTNT_TYPE { get; set; }
        public Nullable<long> LOGO_FILE_SIZE { get; set; }
        public Nullable<System.DateTime> LOGO_UPDATED_AT { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROUP_FILE> GROUP_FILE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROUP_MEMBER> GROUP_MEMBER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROUP_POST> GROUP_POST { get; set; }
    }
}
