//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGE_DOCUMENTS
    {
        public int DOCUMENTID { get; set; }
        public string NAME { get; set; }
        public long SIZE { get; set; }
        public string TYPE { get; set; }
        public byte[] FILECONTENT { get; set; }
        public bool ISDELETED { get; set; }
        public System.DateTime CREATEDON { get; set; }
        public Nullable<System.DateTime> MODIFIEDON { get; set; }
    }
}
