//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class INDIVIDUAL_PAYSLIP_CATGEORY
    {
        public int ID { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<System.DateTime> SAL_DATE { get; set; }
        public string NAME { get; set; }
        public string AMT { get; set; }
        public string IS_DED { get; set; }
        public string INCL_EVRY_MONTH { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
