//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONTHLY_PAYSLIP
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> SAL_DATE { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<int> PYRL_CAT_ID { get; set; }
        public string AMT { get; set; }
        public string IS_APPR { get; set; }
        public Nullable<int> APRV_ID { get; set; }
        public string IS_RJCT { get; set; }
        public Nullable<int> RJCT_ID { get; set; }
        public string RSN { get; set; }
        public string RMRK { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual EMPLOYEE EMPLOYEE1 { get; set; }
        public virtual PAYROLL_CATEGORY PAYROLL_CATEGORY { get; set; }
    }
}
