//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWS_COMMENTS
    {
        public int ID { get; set; }
        public string CNTNT { get; set; }
        public Nullable<int> NEWS_ID { get; set; }
        public Nullable<int> AUTH_ID { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
        public string IS_APPR { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual NEWS NEWS { get; set; }
    }
}
