//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYROLL_CATEGORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAYROLL_CATEGORY()
        {
            this.EMPLOYEE_SALARY_STRUCTURE = new HashSet<EMPLOYEE_SALARY_STRUCTURE>();
            this.MONTHLY_PAYSLIP = new HashSet<MONTHLY_PAYSLIP>();
            this.ARCHIVED_EMPLOYEE_SALARY_STRUCTURE = new HashSet<ARCHIVED_EMPLOYEE_SALARY_STRUCTURE>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<double> PCT { get; set; }
        public Nullable<int> PYRL_CAT_ID { get; set; }
        public bool IS_DED { get; set; }
        public Nullable<bool> STAT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE_SALARY_STRUCTURE> EMPLOYEE_SALARY_STRUCTURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MONTHLY_PAYSLIP> MONTHLY_PAYSLIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARCHIVED_EMPLOYEE_SALARY_STRUCTURE> ARCHIVED_EMPLOYEE_SALARY_STRUCTURE { get; set; }
    }
}
