//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHOTO_MASTER
    {
        public long PHOTOID { get; set; }
        public long GALLERYID { get; set; }
        public string DECRIPTION { get; set; }
        public string THUMBPATH { get; set; }
        public string IMAGEPATH { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string PHOTONAME { get; set; }
    }
}
