//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHOTO_MASTER
    {
        public long PhotoId { get; set; }
        public long GalleryId { get; set; }
        public string Decription { get; set; }
        public string ThumbPath { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string PhotoName { get; set; }
    }
}
