//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class RANKING_LEVEL
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> GPA { get; set; }
        public Nullable<decimal> MKS { get; set; }
        public Nullable<int> SUBJ_CNT { get; set; }
        public Nullable<int> PRIR { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
        public string FULL_CRS { get; set; }
        public Nullable<int> CRS_ID { get; set; }
        public string SUBJ_LMT_TYPE { get; set; }
        public string MKS_LMT_TYPE { get; set; }
    
        public virtual COURSE COURSE { get; set; }
    }
}
