//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class REMINDER
    {
        public int ID { get; set; }
        public Nullable<int> SNDR { get; set; }
        public Nullable<int> RCPNT { get; set; }
        public string SUB { get; set; }
        public string BODY { get; set; }
        public Nullable<bool> IS_READ { get; set; }
        public Nullable<bool> IS_DEL_BY_SNDR { get; set; }
        public Nullable<bool> IS_DEL_BY_RCPNT { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
