//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_LOG
    {
        public int ID { get; set; }
        public string MOBL { get; set; }
        public string GTWY_RESP { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
        public Nullable<int> SMS_MSG_ID { get; set; }
    
        public virtual SMS_MESSAGE SMS_MESSAGE { get; set; }
    }
}
