//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORE_INVENTORY
    {
        public int ID { get; set; }
        public string TITL { get; set; }
        public string DESCR { get; set; }
        public int PRODUCT_ID { get; set; }
        public Nullable<int> BRAND_ID { get; set; }
        public Nullable<int> STORE_ID { get; set; }
        public Nullable<int> UNIT_LEFT { get; set; }
        public Nullable<decimal> COST_PER_UNIT { get; set; }
        public Nullable<decimal> SELL_PRICE_PER_UNIT { get; set; }
        public Nullable<System.DateTime> LAST_SOLD { get; set; }
        public bool IS_ACT { get; set; }
        public bool IS_DEL { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
    
        public virtual STORE_BRAND STORE_BRAND { get; set; }
        public virtual STORE_PRODUCTS STORE_PRODUCTS { get; set; }
    }
}
