//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORE_PURCHAGE
    {
        public int ID { get; set; }
        public int PRODUCT_ID { get; set; }
        public Nullable<int> UNIT_SOLD { get; set; }
        public Nullable<int> SOLD_PRICE { get; set; }
        public string SOLD_BY { get; set; }
        public Nullable<System.DateTime> SOLD_ON { get; set; }
        public string STUDENT_NAME { get; set; }
        public Nullable<long> STUDENT_CONTACT_NO { get; set; }
        public string MONEY_RECEIVED_BY { get; set; }
        public string IS_DEPOSITED { get; set; }
        public string IS_ACT { get; set; }
        public string IS_DEL { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
    
        public virtual STORE_PRODUCTS STORE_PRODUCTS { get; set; }
    }
}
