//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORE_PRODUCTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STORE_PRODUCTS()
        {
            this.STORE_INVENTORY = new HashSet<STORE_INVENTORY>();
            this.STORE_PROCUREMENT = new HashSet<STORE_PROCUREMENT>();
            this.STORE_SELLING = new HashSet<STORE_SELLING>();
            this.STORE_SELLING_BACKUP = new HashSet<STORE_SELLING_BACKUP>();
            this.STORE_SELLING_CART = new HashSet<STORE_SELLING_CART>();
            this.STORE_PURCHAGE_ORDER = new HashSet<STORE_PURCHAGE_ORDER>();
        }
    
        public int PRODUCT_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> CATEGORY_ID { get; set; }
        public Nullable<int> BRAND_ID { get; set; }
        public Nullable<decimal> CURRENT_PRICE { get; set; }
        public Nullable<int> VENDOR_ID { get; set; }
        public string BAR_CODE { get; set; }
        public bool IS_ACT { get; set; }
        public bool IS_DEL { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
        public Nullable<int> SUB_CATEGORY_ID { get; set; }
        public string PRODUCT_CD { get; set; }
        public string DESCR { get; set; }
        public string DEFAULT_UOM { get; set; }
        public Nullable<decimal> AVERAGE_COST { get; set; }
        public string WARRANTY_TERMS { get; set; }
    
        public virtual STORE_BRAND STORE_BRAND { get; set; }
        public virtual STORE_CATEGORY STORE_CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORE_INVENTORY> STORE_INVENTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORE_PROCUREMENT> STORE_PROCUREMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORE_SELLING> STORE_SELLING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORE_SELLING_BACKUP> STORE_SELLING_BACKUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORE_SELLING_CART> STORE_SELLING_CART { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORE_PURCHAGE_ORDER> STORE_PURCHAGE_ORDER { get; set; }
        public virtual STORE_SUB_CATEGORY STORE_SUB_CATEGORY { get; set; }
        public virtual STORE_PURCHAGE_VENDOR STORE_PURCHAGE_VENDOR { get; set; }
    }
}
