//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_PREVIOUS_DATA
    {
        public int ID { get; set; }
        public string INST { get; set; }
        public string YEAR { get; set; }
        public string CRS { get; set; }
        public string TOT_MK { get; set; }
        public Nullable<int> STDNT_ID { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
    }
}
