//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS_ACCESS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERS_ACCESS()
        {
            this.PRIVILEGE_ACCESS = new HashSet<PRIVILEGE_ACCESS>();
        }
    
        public string USR_RIGHTS { get; set; }
        public int USRS_ID { get; set; }
        public string CTL { get; set; }
        public string ACTN { get; set; }
        public int ID { get; set; }
        public bool IS_ACCBLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRIVILEGE_ACCESS> PRIVILEGE_ACCESS { get; set; }
        public virtual USER USER { get; set; }
    }
}
