//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS_ACCESS
    {
        public string USR_ROLE { get; set; }
        public int USRS_ID { get; set; }
        public string LIST_ITEM { get; set; }
        public string LVL_1_MENU { get; set; }
        public string LVL_2_MENU { get; set; }
        public string CTL { get; set; }
        public string ACTN { get; set; }
        public int ID { get; set; }
        public string IS_ACCBLE { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
