//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEEKDAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WEEKDAY()
        {
            this.TIMETABLE_ENTRY = new HashSet<TIMETABLE_ENTRY>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string WKDAY { get; set; }
        public Nullable<int> BTCH_ID { get; set; }
        public Nullable<int> SRT_ORD { get; set; }
        public Nullable<int> DAY_OF_WK { get; set; }
        public string IS_DEL { get; set; }
    
        public virtual BATCH BATCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMETABLE_ENTRY> TIMETABLE_ENTRY { get; set; }
    }
}
